#!/bin/sh
# Regenerates the Homebrew formula for a coldstorage release.
#
#   update-homebrew.sh <version-tag> <checksums.txt> <tap-checkout>
#
# Run by the release workflow after goreleaser has published the archives:
# the checksums file is the release's own, so the formula's shas are the
# published ones by construction.
set -eu

tag="$1"
sums="$2"
tap="$3"

case "$tag" in
	v*) version="${tag#v}" ;;
	*) echo "usage: $0 <v-tag> <checksums.txt> <tap-checkout>" >&2; exit 1 ;;
esac

sha_for() {
	awk -v name="$2" '$2 == name { print $1 }' "$1"
}

mac_arm=$(sha_for "$sums" "coldstorage_${version}_macOS_arm64.tar.gz")
mac_x86=$(sha_for "$sums" "coldstorage_${version}_macOS_x86_64.tar.gz")
lin_arm=$(sha_for "$sums" "coldstorage_${version}_Linux_arm64.tar.gz")
lin_x86=$(sha_for "$sums" "coldstorage_${version}_Linux_x86_64.tar.gz")

for v in "$mac_arm" "$mac_x86" "$lin_arm" "$lin_x86"; do
	[ -n "$v" ] || {
		echo "missing checksum for $v in $sums" >&2
		exit 1
	}
done

mkdir -p "$tap/Formula"
cat >"$tap/Formula/coldstorage.rb" <<EOF
# Generated by coldstorage's release workflow — edits to the version and
# checksums are overwritten on every release.
class Coldstorage < Formula
  desc "Live terminal dashboard for a fleet of git repositories"
  homepage "https://github.com/crueber/coldstorage"
  version "$version"
  license "MIT"

  livecheck do
    url "https://github.com/crueber/coldstorage/releases/latest"
    regex(%r{href=["']?[^/"]*/releases/tag/v?(\d+\.\d+\.\d+)["']}i)
    strategy :page_match
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_macOS_arm64.tar.gz"
      sha256 "$mac_arm"
    else
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_macOS_x86_64.tar.gz"
      sha256 "$mac_x86"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_Linux_arm64.tar.gz"
      sha256 "$lin_arm"
    else
      url "https://github.com/crueber/coldstorage/releases/download/v#{version}/coldstorage_#{version}_Linux_x86_64.tar.gz"
      sha256 "$lin_x86"
    end
  end

  def install
    bin.install "coldstorage"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coldstorage --version")
  end
end
EOF
echo "formula written: $tap/Formula/coldstorage.rb (version $version)"
